name: CI Pipeline
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lab3/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: build -t random-app lab3/task_simple/

      - name: Save Docker image
        run: docker save web-server-image:latest -o lab3/task_simple/build.tar

      - name: List files in build and save to build.txt
        run: ls -R lab3/task_simple/ > lab3/task_simple/build.txt
