name: CI Pipeline
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lab1/**"
      - "lab3/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t web-server-image:latest ./
        working-directory: ./lab1/

      - name: Save Docker image
        run: docker save web-server-image:latest -o ./task_simple/build.tar
        working-directory: ./lab3/

      - name: List files in build and save to build.txt
        run: ls -R ./task_simple/ > ./task_simple/build.txt
        working-directory: ./lab3/
