name: CI Pipeline – lab3
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lab3/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lab3-app lab3/task_simple

      - name: Run lab3 docker image
        run: docker run lab3-app
